apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-cvcs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-cvcs
    app.kubernetes.io/part-of: build-suite-test-mc-ecuq
  name: go-component-cvcs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: go-component-cvcs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: go-component-cvcs
    spec:
      containers:
      - image: python-image:latest
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
